using System;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(menuName = "Data/Building", fileName = "BuildingData")]
public class BuildingSO : ScriptableObject
{
    public List<BuildingData> buildingsData;
}

[Serializable]
public class BuildingData
{
    // Building name for visualization
    [field: SerializeField] public string displayName;
    // Income generated by turn
    [field: SerializeField] public int incomePerTurn;
    // Building Icon (for windows or something like that)
    [field: SerializeField] public Sprite icon;
    // Prefab of building for vizualization
    [field: SerializeField] public GameObject prefab;
}